### ISSUE TITLE
/usr/bin/python3.6 /home/omnisky/graspnetAPI/examples/exam_loadGrasp.py Loading data path...: 100%|██████████| 100/100 [00:00<00:00, 412.06it/s] Traceback (most recent call last):   File "/home/omnisky/graspnetAPI/examples/exam_loadGrasp.py", line 15, in <module>     g = GraspNet(graspnet_root, camera='kinect', split='train')   File "/home/omnisky/graspnetAPI/graspnetAPI/graspnet.py", line 103, in __init__     self.objIds = self.getObjIds(self.sceneIds)   File "/home/omnisky/graspnetAPI/graspnetAPI/graspnet.py", line 148, in getObjIds     f = open(os.path.join(self.root, 'scenes', 'scene_' + str(i).zfill(4), 'object_id_list.txt')) FileNotFoundError: [Errno 2] No such file or directory: '/DATA1/Benchmark/graspnet/scenes/scene_0000/object_id_list.txt'  Process finished with exit code 1

### ISSUE THREAD

**Issue by yhb130353985** [Fang-Haoshu/graspnetAPI#1]
/usr/bin/python3.6 /home/omnisky/graspnetAPI/examples/exam_loadGrasp.py
Loading data path...: 100%|██████████| 100/100 [00:00<00:00, 412.06it/s]
Traceback (most recent call last):
  File "/home/omnisky/graspnetAPI/examples/exam_loadGrasp.py", line 15, in <module>
    g = GraspNet(graspnet_root, camera='kinect', split='train')
  File "/home/omnisky/graspnetAPI/graspnetAPI/graspnet.py", line 103, in __init__
    self.objIds = self.getObjIds(self.sceneIds)
  File "/home/omnisky/graspnetAPI/graspnetAPI/graspnet.py", line 148, in getObjIds
    f = open(os.path.join(self.root, 'scenes', 'scene_' + str(i).zfill(4), 'object_id_list.txt'))
FileNotFoundError: [Errno 2] No such file or directory: '/DATA1/Benchmark/graspnet/scenes/scene_0000/object_id_list.txt'

Process finished with exit code 1

**Comment by Fang-Haoshu** [comment]
Hi, did you download the dataset and modify the graspnet_root?

**Comment by yhb130353985** [comment]
是的，我下载了



发自我的iPhone


------------------ Original ------------------

**Comment by yhb130353985** [comment]
方便加个微信/QQ不， &nbsp;130353985，谢谢



发自我的iPhone


------------------ Original ------------------

**Comment by yhb130353985** [comment]
可以加下我QQ/微信 130353985




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fang-Haoshu/graspnetAPI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月15日(星期六) 晚上8:04
收件人:&nbsp;"Fang-Haoshu/graspnetAPI"<graspnetAPI@noreply.github.com&gt;;
抄送:&nbsp;"Ten."<130353985@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Fang-Haoshu/graspnetAPI] /usr/bin/python3.6 /home/omnisky/graspnetAPI/examples/exam_loadGrasp.py Loading data path...: 100%|██████████| 100/100 [00:00<00:00, 412.06it/s] Traceback (most recent call last):   File "/home/omnisky/graspnetAPI/examples/exam_loadGrasp.py", line 15, in <module&gt;     g = GraspNet(graspnet_root, camera='kinect', split='train')   File "/home/omnisky/graspnetAPI/graspnetAPI/graspnet.py", line 103, in __init__     self.objIds = self.getObjIds(self.sceneIds)   File "/home/omnisky/graspnetAPI/graspnetAPI/graspnet.py", line 148, in getObjIds     f = open(os.path.join(self.root, 'scenes', 'scene_' + str(i).zfill(4), 'object_id_list.txt')) FileNotFoundError:=?UTF-8?Q?_[Errno_





 
Hi, did you download the dataset and modify the graspnet_root?

**Comment by Fang-Haoshu** [comment]
solved
