### ISSUE TITLE
改变图像的像素值

### ISSUE THREAD

**Issue by meiguiz** [Fang-Haoshu/graspnetAPI#15]
刚刚入门，数据集里面的rgb，depth，还有mask label的像素太高了，我该怎么进行缩小。用pillow和Opencv直接将三种图像都resize可以吗？是不是会影响depth里面的三维信息？

**Comment by Fang-Haoshu** [comment]
NOTE: Official version is available at https://github.com/graspnet/graspnetAPI. Please move to this repo

**Comment by Fang-Haoshu** [comment]
不建议resize 会影响depth内参

**Comment by meiguiz** [comment]
感谢这么快的回复！不好意思打扰了。不用resize我是直接用1280x720的像素进行训练吗？还是说进行一个下采样？我这样depths = [cv2.resize(cam['depth'], dsize=(640,480), interpolation=cv2.INTER_NEAREST) ，是不行是吗？抱歉不太懂深度图的信息。
