### ISSUE TITLE
Convert graspnet data into point cloud

### ISSUE THREAD

**Issue by PatrickFeng** [Fang-Haoshu/graspnetAPI#2]
Hi @Fang-Haoshu ,

I noticed that the model takes point cloud as input in your work and I only found RGBD images in GraspNet. I suppose that you get scene point cloud data from RGBD images. (1) Could you share the code of preparing point cloud data? (2) Did you use all RGBD data to generate a single point cloud scene or just part of them? 

Thanks.

**Comment by Fang-Haoshu** [comment]
Hi! you can find the code here: https://github.com/Fang-Haoshu/graspnetAPI/blob/master/graspnetAPI/utils/vis.py#L48

We just use single-view RGBD to generate single-view point cloud.
