### ISSUE TITLE
question about the collision check

### ISSUE THREAD

**Issue by rcao-hk** [Fang-Haoshu/graspnetAPI#5]
Could you give me some advice about the collision check implementation?

Best,

**Comment by Fang-Haoshu** [comment]
Hi, we currently check whether there are scene points in the gripper model's space

**Comment by rcao-hk** [comment]
> Hi, we currently check whether there are scene points in the gripper model's space

Thank you for your reply. Could you detail the process you used for checking the object's point? Which lib or functions you used here? Thank you.

**Comment by Fang-Haoshu** [comment]
You just simply transform the points to the gripper's frame and check several conditions using numpy. For example, max(points) > gripper_width.

**Comment by rcao-hk** [comment]
> You just simply transform the points to the gripper's frame and check several conditions using numpy. For example, max(points) > gripper_width.

Thank you for your reply.
