### ISSUE TITLE
Contact points to score

### ISSUE THREAD

**Issue by ideas-man** [Fang-Haoshu/graspnetAPI#6]
@Fang-Haoshu @chenxi-wang @GouMinghao 

Hi guys!

I've got a problem:
I have grasps that I want to evaluate using the metrics you provide as a eval functionality of you API.
I am getting very low accuracy consistently, though the loss converges and visualization of the predictions shows that while grasps are not ideal, they are far from having very poor accuracy.

After some digging I found out what happens. [This](https://github.com/Fang-Haoshu/graspnetAPI/blob/eval/graspnetAPI/utils/eval_utils.py#L218) part is responsible for getting contact points, and this part spams `None` as a contact for almost all of my grasps:
```python
if len(points_in_gripper) < 10:
    contacts.append(None)
    continue
```
Because of that I get `score` of `-1` [here]():
```python
if contacts[grasp_id] is None:
   scores.append(-1.)
   continue
```

My vis shows that even though some grasps sometimes grasp nothing, it is rare, while eval API consistently returns scores of -1.

This is an example of `scene_100` (red - closer to `grasp.grasp_score` of 2.5, blue - closer to 0):
![0035](https://user-images.githubusercontent.com/60187905/96275073-9528e980-0fd1-11eb-8007-a9317d444156.png)

**Comment by Fang-Haoshu** [comment]
Hi, sorry that I forget to use the objectness score when inference. I just updated the code. You can see inference.py#L127

**Comment by specimen-hub** [comment]
@Fang-Haoshu is this format tested with the API's eval functionality?
