### ISSUE TITLE
Some confusion about GraspNet dataset.

### ISSUE THREAD

**Issue by LCJHust** [Fang-Haoshu/graspnetAPI#7]
Hi:
    Fang, thank you for your excellent work! I have some question about the dataset:
   1) You introduced in paper at Sec3.1 that " Besides, we also provide accurate object 6D pose annotations, rectangle based grasp poses, object masks, and bounding boxes." But I didn't find bounding boxes in annotations or codes on how to process bounding boxes in GraspNetAPI. So, can you release codes about how to process bounding boxes? 
   2) Another question,  are these boxes labeled on images? Can I get 3D bounding boxes with these boxes and camera pose for point cloud detection? 
   3) I visualized the parsed data '_6d_grasp' ，and found that '_6d_grasp[k]['points']' are  points of object surface? Can I get points for the whole scene of each frame?
   Hope for your reply!

**Comment by Fang-Haoshu** [comment]
Hi, seems solved in email.

**Comment by LCJHust** [comment]
> Hi, seems solved in email.

Yeap， thank you~
