### ISSUE TITLE
end-to-end grasp pose prediction network

### ISSUE THREAD

**Issue by hoangcuongbk80** [Fang-Haoshu/graspnetAPI#8]
Hi,

Where could I find the code of your end-to-end grasp pose prediction network?

Thanks in advance!

**Comment by swords123** [comment]
Hello, I'm very interested in your work, when can the end-to-end grasp pose prediction network be available?
THANK YOU!

**Comment by Fang-Haoshu** [comment]
Hi! Thanks for your interest, the code, toolbox and APIs are taking a totally rewrite and will be available in Nov. or Dec.
